os: linux
dist: xenial
language: python
python:
- "3.6"
sudo: false

before_install:
- wget https://repo.anaconda.com/miniconda/Miniconda3-4.5.12-Linux-x86_64.sh
- bash Miniconda3-4.5.12-Linux-x86_64.sh -b -p $HOME/miniconda3
- echo "source $HOME/miniconda3/etc/profile.d/conda.sh" >> $HOME/.bashrc
- source $HOME/.bashrc
- conda activate
- conda env create --name=py36 --file=environment.yaml
- conda activate py36
- rm -f Miniconda3-4.5.12-Linux-x86_64.sh

install:
- python setup.py install

script:
- python tests/all.py

notifications:
  email: false

branches:
  tags: true
  only:
  - master
  - develop