os: linux
dist: xenial
language: python
python:
- "3.6"
sudo: false

before_install:
- MINICONDA_DIR=$HOME/miniconda3
- wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
- bash Miniconda3-latest-Linux-x86_64.sh -b -p $MINICONDA_DIR
- echo "source $MINICONDA_DIR/etc/profile.d/conda.sh" >> $HOME/.bashrc
- source $HOME/.bashrc
- conda activate

install:
- conda env create --name=py36 --file=environment.yaml
- conda activate py36
- python setup.py install

script:
- python tests/all.py

notifications:
  email: false

branches:
  tags: true
  only:
  - master
  - develop