os: linux
dist: xenial
language: python
python:
- "3.6"
sudo: false

before_install:
- MINICONDA_DIR=$HOME/miniconda3
- MINICONDA_BIN=$MINICONDA_DIR/bin
- if [[ -d $MINICONDA_BIN ]]; then
      echo "INFO: Using Miniconda from cache";
    else
      echo "INFO: Installing Miniconda";
      wget https://repo.anaconda.com/miniconda/Miniconda3-4.5.12-Linux-x86_64.sh;
      bash Miniconda3-4.5.12-Linux-x86_64.sh -b -p -u $MINICONDA_DIR;
      rm -f Miniconda3-4.5.12-Linux-x86_64.sh;
  fi;
- echo "source $MINICONDA_DIR/etc/profile.d/conda.sh" >> $HOME/.bashrc
- source $HOME/.bashrc
- conda activate
- conda env create --name=py36 --file=environment.yaml
- conda activate py36

install:
- python setup.py install

script:
- python tests/all.py

cache:
  directories:
  - $HOME/miniconda3

notifications:
  email: false

branches:
  tags: true
  only:
  - master
  - develop