os: linux
dist: xenial
language: python
python:
- "3.6"
sudo: false

before_install:
- export MINICONDA_DIR=$TRAVIS_BUILD_DIR/miniconda3
- wget https://repo.anaconda.com/miniconda/Miniconda3-4.5.12-Linux-x86_64.sh
- bash Miniconda3-4.5.12-Linux-x86_64.sh -b -p $MINICONDA_DIR
- echo "source $MINICONDA_DIR/etc/profile.d/conda.sh" >> $HOME/.bashrc
- source $HOME/.bashrc
- conda activate
- conda env create --name=py36 --file=environment.yaml
- conda activate py36
- rm -f Miniconda3-4.5.12-Linux-x86_64.sh

install:
- python setup.py install

script:
- python tests/all.py

cache:
  directories:
  - miniconda3

notifications:
  email: false

branches:
  tags: true
  only:
  - master
  - develop