os: linux
dist: xenial
language: python
python:
- "3.6"
sudo: false

before_install:
- MINICONDA_DIR=$HOME/miniconda3
- ./misc/install-miniconda.sh
- echo "source $MINICONDA_DIR/etc/profile.d/conda.sh" >> $HOME/.bashrc
- source $HOME/.bashrc
- conda activate
- conda env create --name=py36 --file=environment.yaml
- conda activate py36

install:
- python setup.py install

script:
- python tests/all.py

cache:
  directories:
  - $HOME/miniconda3

notifications:
  email: false

branches:
  tags: true
  only:
  - master
  - develop